### ISSUE TITLE
Entity Metadata Not Found

### ISSUE THREAD

**Issue by bquangDinh** [conceptadev/typeorm-seeding#5]
This error happens when I initialize a new SeedingSource instance like the below (I followed the doc):
```Typescript
export default new SeedingSource({
	dataSource: {
		...(DatabaseConfig as DataSourceOptions),
		database: DatabaseConfig.database as never,
		entities: [__dirname + '/../../resources/**/*.entity{.ts,.js}'],
		synchronize: false, // MUST BE FALSE
	},
	seeders: [
		CreateBase,
		CreateGlassesBill,
		CreatePatient,
		CreateUser,
		CreateProduct,
	],
})
```

`DatabaseConfig` has everything to construct a DataSource

`entities`: It's the path leading to the entities folder. I checked it many many times to make sure it was correct.

But whenever I try to run the seeds, this error appears: `No metadata for "" was found`. This discussion is not about I asking for a solution, because I found one as I described below. It's simply a note for someone who has the same problem as me.

### My solution
So I dug into the code of this project and also compared what TypeORM is actually doing, I figured out that entityMetadata wasn't set during the construction of the DataSource. You have to call `dataSource.initialize()` in order for that to happen.

So I edited the `resolve-data-source.js` like below:

```Javascript
import { DataSource, DataSourceOptions } from 'typeorm'

export const resolveDataSource = async (dataSource: DataSource | DataSourceOptions): DataSource => {
  // create new instance if necessary
  const dataSourceToReturn = dataSource instanceof DataSource ? dataSource : new DataSource(dataSource)

  // Entity Metadatas won't be resolved if we don't call dataSource.initialize()
  // Thus causing error "No metadata for '' not found"
  await dataSourceToReturn.initialize()

  // return the data source
  return dataSourceToReturn
}
```

After this change, the error disappeared. My entities loaded correctly. However, a couple of things need to be changed.
Since `resolveDataSource` now returns a Promise, hence the dataSource instance you get from `SeedingSource` getter is also a Promise. So if seeder class want to access dataSource instance, I did the following:

```Typescript
export default class CreateBase extends Seeder {
	public async run(): Promise<void> {
		const dataSource = await this.seedingSource.dataSource

		...
	}
}
```

And changed the function `save` of factory class in `factory.js` inside the typeorm-seeding folder to:

```Javascript
async save(entities, saveOptions) {
        const dataSource = await this.seedingSource.dataSource;
        // has been initialized yet?
        if (!dataSource.isInitialized) {
            // no, initialize it
            await dataSource.initialize();
        }
        return dataSource.createEntityManager().save(entities, saveOptions);
    }
```

Now everything works!

### Footnote
I don't know if this thing is related to this topic, but anyway, I set `synchronize: false, // MUST BE FALSE` because if it is set to true, TypeORM will do crazy things without you even asking for it. In my case, it was trying to drop indexes of my tables when I didn't ask it to do.

**Comment by MrMaz** [comment]
Thank you for reporting this. I will try to reproduce this on my end and report back.

Which version of TypeORM do you have installed?

**Comment by bquangDinh** [comment]
I use TypeORM v0.3.12

**Comment by MrMaz** [comment]
@bquangDinh you mentioned a change you made to the `Factory.save()` method, but the source already contains this initialization... here is a link to the code on `main`.

https://github.com/conceptadev/typeorm-seeding/blob/main/src/factory.ts#L119

Can you confirm the version of this project you are on?

**Comment by bquangDinh** [comment]
Yes I have that in my version. The thing is, with the code is arranged your way, that means TypeORM will be first initialized when you call saving (I tried to see if TypeORM is initialize somewhere else but couldn't find it so I assume this is the only one you call `initialize`) In my case, it isn't right. Since my seeds need to query something in the database before calling `save`. That's why I got the error. My quick solution in the moment is calling `initialize` on every seeds to make sure TypeORM is good to go. But it's kinda annoying tho since I have to do it on every seeds.

**Comment by MrMaz** [comment]
> Yes I have that in my version. The thing is, with the code is arranged your way, that means TypeORM will be first initialized when you call saving (I tried to see if TypeORM is initialize somewhere else but couldn't find it so I assume this is the only one you call `initialize`) In my case, it isn't right. Since my seeds need to query something in the database before calling `save`. That's why I got the error. My quick solution in the moment is calling `initialize` on every seeds to make sure TypeORM is good to go. But it's kinda annoying tho since I have to do it on every seeds.

I found the issue, but no solution yet. It only happens when you provide a path for an entity. If you import the entity class and put it directly on the entities array, it works fine.

I thought providing a string path was deprecated on 0.3.X... but maybe I was mistaken, or they added it back since 0.3.0.

I will continue testing here, and try to release a fix soon.

**Comment by bquangDinh** [comment]
Well, I tried to put entities file also, but it didn't work, the error was still there. That's why I had to go through the code to see if TypeORM actually doing anything at all in constructor. It turned out TypeORM doesn't build entity metadata in the constructor, all it does is create some variables and that's it.

This is the code I found in `Datasource.js` from my TypeORM:

```Javascript
    constructor(options) {
        this["@instanceof"] = Symbol.for("DataSource");
        /**
         * Migration instances that are registered for this connection.
         */
        this.migrations = [];
        /**
         * Entity subscriber instances that are registered for this connection.
         */
        this.subscribers = [];
        /**
         * All entity metadatas that are registered for this connection.
         */
        this.entityMetadatas = [];
        this.name = options.name || "default";
        this.options = options;
        this.logger = new LoggerFactory_1.LoggerFactory().create(this.options.logger, this.options.logging);
        this.driver = new DriverFactory_1.DriverFactory().create(this);
        this.manager = this.createEntityManager();
        this.namingStrategy =
            options.namingStrategy || new DefaultNamingStrategy_1.DefaultNamingStrategy();
        this.metadataTableName = options.metadataTableName || "typeorm_metadata";
        this.queryResultCache = options.cache
            ? new QueryResultCacheFactory_1.QueryResultCacheFactory(this).create()
            : undefined;
        this.relationLoader = new RelationLoader_1.RelationLoader(this);
        this.relationIdLoader = new RelationIdLoader_1.RelationIdLoader(this);
        this.isInitialized = false;
    }
```

As you can see, it barely does anything with `entityMetadatas`  array. 

And it only does so in `initialize()`

```Javascript
    /**
     * Performs connection to the database.
     * This method should be called once on application bootstrap.
     * This method not necessarily creates database connection (depend on database type),
     * but it also can setup a connection pool with database to use.
     */
    async initialize() {
        if (this.isInitialized)
            throw new error_1.CannotConnectAlreadyConnectedError(this.name);
        // connect to the database via its driver
        await this.driver.connect()
        // connect to the cache-specific database if cache is enabled
        if (this.queryResultCache)
            await this.queryResultCache.connect();
        // set connected status for the current connection
        ObjectUtils_1.ObjectUtils.assign(this, { isInitialized: true });
        try {
            // ----> this line: build all metadatas registered in the current connection
            await this.buildMetadatas();
            await this.driver.afterConnect();
            // if option is set - drop schema once connection is done
            if (this.options.dropSchema)
                await this.dropDatabase();
            // if option is set - automatically synchronize a schema
            if (this.options.migrationsRun)
                await this.runMigrations({
                    transaction: this.options.migrationsTransactionMode,
                });
            // if option is set - automatically synchronize a schema
            if (this.options.synchronize)
                await this.synchronize();
        }
        catch (error) {
            // if for some reason build metadata fail (for example validation error during entity metadata check)
            // connection needs to be closed
            await this.destroy();
            throw error;
        }
        return this;
    }
```

**Comment by bquangDinh** [comment]
But I'll close the issue anyway since I've fixed it

**Comment by MrMaz** [comment]
Can you post a short example of how you are making queries before save? After digging into the code, I see how there are cases where if you don't initialize the DataSource manually before passing to the SeedingSource options there will be no initialization done.

I am just curious about your pattern so I can make sure I cover these scenarios. Are you making queries inside the Factory classes, or inside the Seeder classes, or both?

**Comment by bquangDinh** [comment]
I make queries inside the Seeder classes. This is one example of how I seed the Products table. Since each product needs an authorizer, and I want it to be randomly selected. So I have to perform a query to the database to get user ids before saving products into database

```Typescript
export default class CreateProduct extends Seeder {
	public async run(): Promise<void> {
		// make sure it's initialized
		const dataSource = this.seedingSource.dataSource

		if (!dataSource.isInitialized) {
			await this.seedingSource.dataSource.initialize()
		}

		const products = await this.factory(ProductFactory).makeMany(100)

		const repo = dataSource.getRepository(Product)

		const authorizerIds: { id: string }[] = await dataSource
			.getRepository(User)
			.createQueryBuilder('user')
			.select('id')
			.getRawMany()

		if (authorizerIds.length === 0) {
			console.warn('No user found in database. Need seed!')
			return
		}

		for (const product of products) {
			const existingProduct = await repo.findOne({
				where: {
					productCode: product.productCode,
				},
			})

			if (existingProduct) {
				product.quantity += existingProduct.quantity
				product.id = existingProduct.id
			} else {
				product.authorizerId = sample(authorizerIds).id
			}

			await dataSource.getRepository(Product).save(product)
		}
	}
}
```

**Comment by MrMaz** [comment]
@bquangDinh Please take a look at this PR and let me know if you think it will solve your issue. I also added some helpers for getting repositories inside seeder and factory classes.

https://github.com/conceptadev/typeorm-seeding/pull/6

Since this issue is closed, you can make comments on the PR itself 👍🏻
